config/routes.rb
Rails.application.routes.draw do
  ### Setup a simple messaging server
  resources :messages, only: [:index, :create]
  resources :sessions, only: [:new, :create] do
    get :logout, on: :collection
  end
  ### Login page is the default
  root "sessions#new"

  namespace :admin do
    resources :stats, only: [:index]
  end

  # Serve websocket cable requests in-process
  mount ActionCable.server => "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin/stats_controller.rb
class Admin::StatsController < ApplicationController
  layout "admin"

  before_action :check_user_is_admin

  def index
    # render /app/views/admin/stats/index.html.erb
  end

  private

  def check_user_is_admin
    true # or whatever
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    # render /app/views/messages/index.html.erb
  end

  def create
    ActionCable.server.broadcast(
      "messages",
      username: cookies.signed[:username],
      message: params[:message][:body],
    )

    ActionCable.server.broadcast("stats", kind: "message")
    head :ok
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # render /app/views/sessions/new.html.erb
  end

  def create
    cookies.signed[:username] = params[:session][:username]
    ActionCable.server.broadcast("stats", kind: "login")
    redirect_to messages_path
  end

  def logout
    cookies.delete(:username)
    ActionCable.server.broadcast("stats", kind: "logout")
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/stats/index.html.erb
<div id="chart-container-js" style="height: 300px; width:100%;">
</div>


<a id="WHATVER" href="whatever">KICK OUT ERRRYBODY</a>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IndyrbActioncable Admin</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "admin", "data-turbolinks-track" => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IndyrbActioncable</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
Signed in as @<%= cookies.signed[:username] %>. <%= link_to "Logout", logout_sessions_path %>
<br/><br/>

<table>
  <tr>
    <td>
      <%= form_for :message, url: messages_path, remote: true, html: { id: "messages-form" } do |f| %>
        <%= f.label :body, "Enter a message:"  %><br/>
        <%= f.text_field :body %><br/>
        <%= f.submit "Send message" %>
      <% end %>
    </td>
    <td>
      <a id="bongo" href="#" title="play bongo"><img src="<%= asset_path("bongo-drum.png") %>" /></a>
    </td>
  </tr>
</table>

<div id="messages"></div>
<br/><br/>